name: Kernel Build Workflow

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Model to build (leave empty to build all)"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - d1
          - d1xks
          - d2s
          - d2x
          - d2xks

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      model: ${{ github.event.inputs.model }}
    steps:
      - name: Set model output
        run: echo "model=${{ github.event.inputs.model }}" >> $GITHUB_OUTPUT


  build:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        model: [d1, d1xks, d2s, d2x, d2xks]

    steps:
      - name: Skip unwanted models
        if: ${{ needs.setup.outputs.model != 'all' && needs.setup.outputs.model != matrix.model }}
        run: echo "Skipping build for ${{ matrix.model }}"

      - name: Stop job if skipped
        if: ${{ needs.setup.outputs.model != 'all' && needs.setup.outputs.model != matrix.model }}
        run: exit 0

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --remote

      - name: Build kernel (${{ matrix.model }})
        run: ./workflows.sh -m ${{ matrix.model }} -k Y -r N

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExtremeKRNL-${{ matrix.model }}
          path: build/out/${{ matrix.model }}/zip
